# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hood')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
